# Generated by Django 5.1.5 on 2025-01-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_likedlistings'),
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedListings',
            new_name='LikedListing',
        ),
    ]
